// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4df9c2fd34584587 "copy of lab: www.lab.zeitlabs.com", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'mobile' // Variant
 * banner?: {src: string, srcSet?: string, alt?: string} // banner
 * title?: string // Title
 * featured?: boolean // Featured
 * courseLevel?: string // course level
 * price?: string // price
 * link?: string // Link
 * courseDescription?: any // course description
}} Props

 */
import {
	Icon as Icon2,
	className,
	className2,
	className3,
	className4,
	className5 as className6,
	css,
	css2,
	css3,
	css4,
	css5 as css6,
	fonts,
	fonts2,
	fonts3,
	fonts4,
	fonts5 as fonts6,
	withOneLineEllipsis,
	withTwoLineEllipsis,
} from "../chunks/chunk-VLJCZSNN.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "../chunks/chunk-GLFSMVSA.js";
import { Icon } from "../chunks/chunk-WQJQY4NG.js";
import "../chunks/chunk-HR56UER2.js";
import { routes } from "../chunks/chunk-SCLW5GNH.js";

// virtual:cards/course-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/49QCe7vdN6V9rz964rmr/YDrcL98OGZPsXu7KLsXO/pl2QHGxGN.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCodeBoundaryForOverrides,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var RichTextWithOneLineEllipsis14zxbuj = withCodeBoundaryForOverrides(
	RichText,
	{
		nodeId: "Ghl5eJctv",
		override: withOneLineEllipsis,
		scopeId: "pl2QHGxGN",
	},
);
var RichTextWithTwoLineEllipsiskvg7m7 = withCodeBoundaryForOverrides(RichText, {
	nodeId: "Tdbz7JzLj",
	override: withTwoLineEllipsis,
	scopeId: "pl2QHGxGN",
});
var MaterialFonts = getFonts(Icon2);
var enabledGestures = {
	D9ehAnSPE: {
		hover: true,
	},
};
var cycleOrder = ["D9ehAnSPE", "Gc5Zaa1Wr"];
var serializationHash = "framer-c3HI1";
var variantClassNames = {
	D9ehAnSPE: "framer-v-586095",
	Gc5Zaa1Wr: "framer-v-1axtzjk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.5,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	desktop: "D9ehAnSPE",
	mobile: "Gc5Zaa1Wr",
};
var getProps = ({
	banner,
	courseDescription,
	courseLevel,
	featured,
	height,
	id,
	link,
	price,
	title,
	width,
	...props
}) => {
	return {
		...props,
		KNC8xpWIk: banner ?? props.KNC8xpWIk,
		OaayPRH4w: link ?? props.OaayPRH4w,
		pEF0bZcH9: courseDescription ?? props.pEF0bZcH9 ?? (
			<React.Fragment>
				<motion.p>{"course description"}</motion.p>
			</React.Fragment>
		),
		q9Uv_Sx1O: courseLevel ?? props.q9Uv_Sx1O ?? "Beginner",
		qX_Xj7hhd: title ?? props.qX_Xj7hhd ?? "Web Design Course ",
		tGnvRRNsj: featured ?? props.tGnvRRNsj ?? true,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "D9ehAnSPE",
		WkpzrrhOR: price ?? props.WkpzrrhOR ?? "99",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		KNC8xpWIk,
		qX_Xj7hhd,
		tGnvRRNsj,
		q9Uv_Sx1O,
		WkpzrrhOR,
		OaayPRH4w,
		pEF0bZcH9,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "D9ehAnSPE",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className,
		className6,
		className5,
		className3,
		className4,
		className2,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={OaayPRH4w}
						motionChild={true}
						nodeId={"D9ehAnSPE"}
						openInNewTab={false}
						scopeId={"pl2QHGxGN"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-586095", className7, classNames)} framer-18gqr98`}
							data-framer-name={"desktop"}
							layoutDependency={layoutDependency}
							layoutId={"D9ehAnSPE"}
							ref={refBinding}
							style={{
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
								...style,
							}}
							{...addPropertyOverrides(
								{
									"D9ehAnSPE-hover": {
										"data-framer-name": void 0,
									},
									Gc5Zaa1Wr: {
										"data-framer-name": "mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-2u2tyt"}
								data-border={true}
								data-framer-name={"container"}
								layoutDependency={layoutDependency}
								layoutId={"whNiUfkZq"}
								style={{
									"--border-bottom-width": "3px",
									"--border-color": "rgb(255, 255, 255)",
									"--border-left-width": "3px",
									"--border-right-width": "3px",
									"--border-style": "solid",
									"--border-top-width": "3px",
									background:
										"linear-gradient(0deg, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0.5) 100%)",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									boxShadow: "0px 10px 30px 0px rgba(0, 0, 0, 0.1)",
									rotateY: 0,
									transformPerspective: 1200,
								}}
								variants={{
									"D9ehAnSPE-hover": {
										rotateY: -20,
									},
								}}
							>
								<motion.div
									className={"framer-sg4nu3"}
									data-framer-name={"content"}
									layoutDependency={layoutDependency}
									layoutId={"KizWY7jxz"}
									style={{
										transformPerspective: 1200,
									}}
								>
									<Image
										background={{
											alt: "",
											fit: "fill",
											sizes: `max(${componentViewport?.width || "100vw"} - 48px, 1px)`,
											...toResponsiveImage(KNC8xpWIk),
											...{
												positionX: "center",
												positionY: "center",
											},
										}}
										className={"framer-1w0exhq"}
										layoutDependency={layoutDependency}
										layoutId={"e_TK6IVEC"}
										style={{
											borderBottomLeftRadius: 16,
											borderBottomRightRadius: 16,
											borderTopLeftRadius: 16,
											borderTopRightRadius: 16,
										}}
									/>
									<motion.div
										className={"framer-tqodp"}
										data-framer-name={"rating & price"}
										layoutDependency={layoutDependency}
										layoutId={"Ff0Sgxcap"}
										style={{
											opacity: 0.8,
										}}
									>
										<motion.div
											className={"framer-1p4l81w"}
											data-framer-name={"rating"}
											layoutDependency={layoutDependency}
											layoutId={"GK3BjdK3m"}
										>
											<ComponentViewportProvider>
												<SmartComponentScopedContainer
													className={"framer-1he1zen-container"}
													isAuthoredByUser={true}
													isModuleExternal={true}
													layoutDependency={layoutDependency}
													layoutId={"RM0xWB_VS-container"}
													nodeId={"RM0xWB_VS"}
													rendersWithMotion={true}
													scopeId={"pl2QHGxGN"}
												>
													<Icon
														color={"rgb(255, 204, 0)"}
														height={"100%"}
														iconSearch={"star"}
														iconSelection={"House"}
														id={"RM0xWB_VS"}
														layoutId={"RM0xWB_VS"}
														mirrored={false}
														selectByList={false}
														style={{
															height: "100%",
															width: "100%",
														}}
														weight={"fill"}
														width={"100%"}
													/>
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider>
												<SmartComponentScopedContainer
													className={"framer-49ccdi-container"}
													isAuthoredByUser={true}
													isModuleExternal={true}
													layoutDependency={layoutDependency}
													layoutId={"ZEFNrms7O-container"}
													nodeId={"ZEFNrms7O"}
													rendersWithMotion={true}
													scopeId={"pl2QHGxGN"}
												>
													<Icon
														color={"rgb(255, 204, 0)"}
														height={"100%"}
														iconSearch={"star"}
														iconSelection={"House"}
														id={"ZEFNrms7O"}
														layoutId={"ZEFNrms7O"}
														mirrored={false}
														selectByList={false}
														style={{
															height: "100%",
															width: "100%",
														}}
														weight={"fill"}
														width={"100%"}
													/>
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider>
												<SmartComponentScopedContainer
													className={"framer-112hn3g-container"}
													isAuthoredByUser={true}
													isModuleExternal={true}
													layoutDependency={layoutDependency}
													layoutId={"IP9i61kyX-container"}
													nodeId={"IP9i61kyX"}
													rendersWithMotion={true}
													scopeId={"pl2QHGxGN"}
												>
													<Icon
														color={"rgb(255, 204, 0)"}
														height={"100%"}
														iconSearch={"star"}
														iconSelection={"House"}
														id={"IP9i61kyX"}
														layoutId={"IP9i61kyX"}
														mirrored={false}
														selectByList={false}
														style={{
															height: "100%",
															width: "100%",
														}}
														weight={"fill"}
														width={"100%"}
													/>
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider>
												<SmartComponentScopedContainer
													className={"framer-fjlp4x-container"}
													isAuthoredByUser={true}
													isModuleExternal={true}
													layoutDependency={layoutDependency}
													layoutId={"aL9CfHtFP-container"}
													nodeId={"aL9CfHtFP"}
													rendersWithMotion={true}
													scopeId={"pl2QHGxGN"}
												>
													<Icon
														color={"rgb(255, 204, 0)"}
														height={"100%"}
														iconSearch={"star"}
														iconSelection={"House"}
														id={"aL9CfHtFP"}
														layoutId={"aL9CfHtFP"}
														mirrored={false}
														selectByList={false}
														style={{
															height: "100%",
															width: "100%",
														}}
														weight={"fill"}
														width={"100%"}
													/>
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider>
												<SmartComponentScopedContainer
													className={"framer-1gnu2pz-container"}
													isAuthoredByUser={true}
													isModuleExternal={true}
													layoutDependency={layoutDependency}
													layoutId={"VvPyY5P2Q-container"}
													nodeId={"VvPyY5P2Q"}
													rendersWithMotion={true}
													scopeId={"pl2QHGxGN"}
												>
													<Icon
														color={"rgb(255, 204, 0)"}
														height={"100%"}
														iconSearch={"star"}
														iconSelection={"House"}
														id={"VvPyY5P2Q"}
														layoutId={"VvPyY5P2Q"}
														mirrored={false}
														selectByList={false}
														style={{
															height: "100%",
															width: "100%",
														}}
														weight={"fill"}
														width={"100%"}
													/>
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										</motion.div>
										<motion.div
											className={"framer-p1lyhv"}
											data-framer-name={"price"}
											layoutDependency={layoutDependency}
											layoutId={"LY8IZAXnC"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-s9gwwf"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"lEDYUnIUO"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h4
														className={"framer-styles-preset-edb2g0"}
														data-styles-preset={"RsabAHyCl"}
													>
														{"$"}
													</motion.h4>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-f6y2x5"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"GM5gmdkpm"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={WkpzrrhOR}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h4
														className={"framer-styles-preset-edb2g0"}
														data-styles-preset={"RsabAHyCl"}
													>
														{"$"}
													</motion.h4>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
									<RichTextWithOneLineEllipsis14zxbuj
										__fromCanvasComponent={true}
										className={"framer-14zxbuj"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Ghl5eJctv"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={qX_Xj7hhd}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h4
												className={"framer-styles-preset-edb2g0"}
												data-styles-preset={"RsabAHyCl"}
											>
												{"Web Deasign Course "}
											</motion.h4>
										</React.Fragment>
									</RichTextWithOneLineEllipsis14zxbuj>
									<RichTextWithTwoLineEllipsiskvg7m7
										__fromCanvasComponent={true}
										className={"framer-kvg7m7"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Tdbz7JzLj"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											opacity: 0.8,
										}}
										stylesPresetsClassNames={{
											a: "framer-styles-preset-1eptntn",
											h1: "framer-styles-preset-iek49t",
											h2: "framer-styles-preset-1nepf4k",
											h3: "framer-styles-preset-l7dt38",
											h4: "framer-styles-preset-edb2g0",
											p: "framer-styles-preset-prw4x",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										{pEF0bZcH9}
									</RichTextWithTwoLineEllipsiskvg7m7>
									<motion.div
										className={"framer-n1t5h5"}
										data-framer-name={"tags"}
										layoutDependency={layoutDependency}
										layoutId={"tBdLrn8Vv"}
									>
										{tGnvRRNsj && (
											<motion.div
												className={"framer-d3x3fs"}
												data-framer-name={"featured tag"}
												layoutDependency={layoutDependency}
												layoutId={"oMVAUSS5M"}
												style={{
													backgroundColor:
														"var(--token-065d10ce-0cf2-4b09-9a28-c529426d3480, rgba(129, 79, 255, 0.15))",
													borderBottomLeftRadius: 8,
													borderBottomRightRadius: 8,
													borderTopLeftRadius: 8,
													borderTopRightRadius: 8,
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-vv7zje"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"ra2vtoaF6"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-a1111099-e2fd-4b6d-9c9f-7c369c85dc98, rgb(129, 79, 255))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-prw4x"}
															data-styles-preset={"n6ak1dmIx"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-a1111099-e2fd-4b6d-9c9f-7c369c85dc98, rgb(129, 79, 255)))",
															}}
														>
															{"Featured"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
										)}
										<motion.div
											className={"framer-14wdkbp"}
											data-framer-name={"level"}
											layoutDependency={layoutDependency}
											layoutId={"c6YhKBz6Q"}
											style={{
												opacity: 0.8,
											}}
										>
											<ComponentViewportProvider>
												<SmartComponentScopedContainer
													className={"framer-mz7lmw-container"}
													isAuthoredByUser={true}
													isModuleExternal={true}
													layoutDependency={layoutDependency}
													layoutId={"qACBpAazQ-container"}
													nodeId={"qACBpAazQ"}
													rendersWithMotion={true}
													scopeId={"pl2QHGxGN"}
													style={{
														opacity: 0.7,
													}}
												>
													<Icon2
														color={
															"var(--token-e59aa7d3-7c6b-40e9-94c0-b5677a71684a, rgb(0, 0, 0))"
														}
														height={"100%"}
														iconSearch={"Home"}
														iconSelection={"BarChart"}
														iconStyle15={"Filled"}
														iconStyle2={"Filled"}
														iconStyle7={"Filled"}
														id={"qACBpAazQ"}
														layoutId={"qACBpAazQ"}
														mirrored={false}
														selectByList={true}
														style={{
															height: "100%",
															width: "100%",
														}}
														width={"100%"}
													/>
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-4874g"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"B3BIbN8FE"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={q9Uv_Sx1O}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-prw4x"}
														data-styles-preset={"n6ak1dmIx"}
													>
														{"Beginner"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-c3HI1.framer-18gqr98, .framer-c3HI1 .framer-18gqr98 { display: block; }",
	".framer-c3HI1.framer-586095 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 360px; }",
	".framer-c3HI1 .framer-2u2tyt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 24px 24px 32px 24px; position: relative; transform-style: preserve-3d; width: 100%; z-index: 1; }",
	".framer-c3HI1 .framer-sg4nu3 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; transform-style: preserve-3d; width: 1px; z-index: 3; }",
	".framer-c3HI1 .framer-1w0exhq { aspect-ratio: 1.538812785388128 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 203px); overflow: visible; position: relative; width: 100%; }",
	".framer-c3HI1 .framer-tqodp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-c3HI1 .framer-1p4l81w { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-c3HI1 .framer-1he1zen-container, .framer-c3HI1 .framer-49ccdi-container, .framer-c3HI1 .framer-112hn3g-container, .framer-c3HI1 .framer-fjlp4x-container, .framer-c3HI1 .framer-1gnu2pz-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 21px); position: relative; width: 17px; }",
	".framer-c3HI1 .framer-p1lyhv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-c3HI1 .framer-s9gwwf, .framer-c3HI1 .framer-f6y2x5, .framer-c3HI1 .framer-vv7zje, .framer-c3HI1 .framer-4874g { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-c3HI1 .framer-14zxbuj, .framer-c3HI1 .framer-kvg7m7 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-c3HI1 .framer-n1t5h5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-c3HI1 .framer-d3x3fs { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 4px 16px 4px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-c3HI1 .framer-14wdkbp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-c3HI1 .framer-mz7lmw-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 28px); position: relative; width: 24px; }",
	...css,
	...css6,
	...css5,
	...css3,
	...css4,
	...css2,
	'.framer-c3HI1[data-border="true"]::after, .framer-c3HI1 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerpl2QHGxGN = withCSS(Component, css7, "framer-c3HI1");
var stdin_default = Framerpl2QHGxGN;
Framerpl2QHGxGN.displayName = "Cards / Course card";
Framerpl2QHGxGN.defaultProps = {
	height: 435,
	width: 360,
};
addPropertyControls(Framerpl2QHGxGN, {
	variant: {
		options: ["D9ehAnSPE", "Gc5Zaa1Wr"],
		optionTitles: ["desktop", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	KNC8xpWIk: {
		title: "banner",
		type: ControlType.ResponsiveImage,
	},
	qX_Xj7hhd: {
		defaultValue: "Web Design Course ",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	tGnvRRNsj: {
		defaultValue: true,
		title: "Featured",
		type: ControlType.Boolean,
	},
	q9Uv_Sx1O: {
		defaultValue: "Beginner",
		displayTextArea: false,
		title: "course level",
		type: ControlType.String,
	},
	WkpzrrhOR: {
		defaultValue: "99",
		title: "price",
		type: ControlType.String,
	},
	OaayPRH4w: {
		title: "Link",
		type: ControlType.Link,
	},
	pEF0bZcH9: {
		defaultValue: "<p>course description</p>",
		title: "course description",
		type: ControlType.RichText,
	},
});
addFonts(
	Framerpl2QHGxGN,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...MaterialFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cards/course-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Gc5Zaa1Wr",
	xl: "D9ehAnSPE",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4df9c2fd34584587fe45f619be728920d85179ab84c9e42fdab9b2984ca18da4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CourseCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4df9c2fd34584587fe45f619be728920d85179ab84c9e42fdab9b2984ca18da4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var course_card_default = ComponentWithRoot;
export { course_card_default as default };
